package com.example.classparticipation

interface SubjectInterface {
    var sbj_name : String
    fun name(): String {
        return sbj_name
    }
    fun description() :String
    fun intro() : String{
        return "This is info about: $sbj_name"
    }
}
class HumanInterface : SubjectInterface{
    override var sbj_name : String = "Temirlan"
    override fun intro() :String {
        return super.intro()
    }
    override fun description() : String {
        return "Temirlan Temirov connects online brands to their target audiences for the perfect marketing experience. At the University of California, Davis, Karmen learned the importance of applying classic marketing techniques to modern brand strategies from experts in the field, including her Communications professor, Dr. Martin Mitchell. Recently she finished a research paper on customer conversion and participated in a group project on improving SEO. Karmen is currently finishing her Bachelor of Arts in Communications and hopes to intern in an online marketing department in the near future."
    }
}
class AnimalInterface : SubjectInterface{
    override var sbj_name : String = "Dog"
    override fun intro() :String {
        return super.intro()
    }
    override fun description(): String {
  return "Dogs are generally much better at conserving heat than at cooling themselves. In sled dogs, who can survive outdoors even in bitterly cold temperatures, the fur acts as an insulating “blanket” that retains the heat generated by the dog’s high metabolism. "   }
}

class PlantInterface : SubjectInterface{
    override var sbj_name : String = "Aloe"
    override fun intro(): String  {
        return super.intro()
    }
    override fun description() :String {
        return "Aloe vera is a stemless or very short-stemmed plant growing to 60–100 centimetres (24–39 inches) tall, spreading by offsets. The leaves are thick and fleshy, green to grey-green, with some varieties showing white flecks on their upper and lower stem surfaces."  }
}


